// Code generated by protoc-gen-go.
// source: distribution.proto
// DO NOT EDIT!

/*
Package trackers is a generated protocol buffer package.

syntax = "proto3";

It is generated from these files:
	distribution.proto

It has these top-level messages:
	DistributionMsg
	DistributionComparison
*/
package trackers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DistributionMsg struct {
	DeviceId         *string `protobuf:"bytes,1,req,name=DeviceId" json:"DeviceId,omitempty"`
	BootId           *string `protobuf:"bytes,2,req,name=BootId" json:"BootId,omitempty"`
	Temps            []int32 `protobuf:"varint,3,rep,name=Temps" json:"Temps,omitempty"`
	Timestamps       []int64 `protobuf:"varint,4,rep,name=Timestamps" json:"Timestamps,omitempty"`
	Period           *int64  `protobuf:"varint,5,req,name=Period" json:"Period,omitempty"`
	IsFull           *bool   `protobuf:"varint,6,req,name=IsFull" json:"IsFull,omitempty"`
	NumEntries       *int64  `protobuf:"varint,7,req,name=NumEntries" json:"NumEntries,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DistributionMsg) Reset()                    { *m = DistributionMsg{} }
func (m *DistributionMsg) String() string            { return proto.CompactTextString(m) }
func (*DistributionMsg) ProtoMessage()               {}
func (*DistributionMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DistributionMsg) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *DistributionMsg) GetBootId() string {
	if m != nil && m.BootId != nil {
		return *m.BootId
	}
	return ""
}

func (m *DistributionMsg) GetTemps() []int32 {
	if m != nil {
		return m.Temps
	}
	return nil
}

func (m *DistributionMsg) GetTimestamps() []int64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *DistributionMsg) GetPeriod() int64 {
	if m != nil && m.Period != nil {
		return *m.Period
	}
	return 0
}

func (m *DistributionMsg) GetIsFull() bool {
	if m != nil && m.IsFull != nil {
		return *m.IsFull
	}
	return false
}

func (m *DistributionMsg) GetNumEntries() int64 {
	if m != nil && m.NumEntries != nil {
		return *m.NumEntries
	}
	return 0
}

type DistributionComparison struct {
	Dist1            *DistributionMsg `protobuf:"bytes,1,req,name=dist1" json:"dist1,omitempty"`
	Dist2            *DistributionMsg `protobuf:"bytes,2,req,name=dist2" json:"dist2,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *DistributionComparison) Reset()                    { *m = DistributionComparison{} }
func (m *DistributionComparison) String() string            { return proto.CompactTextString(m) }
func (*DistributionComparison) ProtoMessage()               {}
func (*DistributionComparison) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DistributionComparison) GetDist1() *DistributionMsg {
	if m != nil {
		return m.Dist1
	}
	return nil
}

func (m *DistributionComparison) GetDist2() *DistributionMsg {
	if m != nil {
		return m.Dist2
	}
	return nil
}

func init() {
	proto.RegisterType((*DistributionMsg)(nil), "trackers.DistributionMsg")
	proto.RegisterType((*DistributionComparison)(nil), "trackers.DistributionComparison")
}

func init() { proto.RegisterFile("distribution.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xc9, 0x2c, 0x2e,
	0x29, 0xca, 0x4c, 0x2a, 0x2d, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x28, 0x29, 0x4a, 0x4c, 0xce, 0x4e, 0x2d, 0x2a, 0x56, 0x3a, 0xcd, 0xc8, 0xc5, 0xef, 0x82, 0xa4,
	0xc0, 0xb7, 0x38, 0x5d, 0x48, 0x8a, 0x8b, 0xc3, 0x25, 0xb5, 0x2c, 0x33, 0x39, 0xd5, 0x33, 0x45,
	0x82, 0x51, 0x81, 0x49, 0x83, 0x33, 0x08, 0xce, 0x17, 0x12, 0xe3, 0x62, 0x73, 0xca, 0xcf, 0x2f,
	0x01, 0xca, 0x30, 0x81, 0x65, 0xa0, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0x90, 0xd4, 0xdc, 0x82, 0x62,
	0x09, 0x66, 0x05, 0x66, 0x0d, 0xd6, 0x20, 0x08, 0x47, 0x48, 0x8e, 0x8b, 0x2b, 0x24, 0x33, 0x37,
	0xb5, 0xb8, 0x24, 0x11, 0x24, 0xc5, 0x02, 0x94, 0x62, 0x0e, 0x42, 0x12, 0x01, 0x99, 0x16, 0x90,
	0x5a, 0x94, 0x99, 0x9f, 0x22, 0xc1, 0x0a, 0x34, 0x8d, 0x39, 0x08, 0xca, 0x03, 0x89, 0x7b, 0x16,
	0xbb, 0x95, 0xe6, 0xe4, 0x48, 0xb0, 0x01, 0xc5, 0x39, 0x82, 0xa0, 0x3c, 0x90, 0x79, 0x7e, 0xa5,
	0xb9, 0xae, 0x79, 0x40, 0xe7, 0xa6, 0x16, 0x4b, 0xb0, 0x83, 0xf5, 0x20, 0x89, 0x28, 0x55, 0x71,
	0x89, 0x21, 0x7b, 0xc6, 0x39, 0x3f, 0xb7, 0x20, 0xb1, 0x28, 0xb3, 0x38, 0x3f, 0x4f, 0x48, 0x9f,
	0x8b, 0x15, 0x14, 0x0e, 0x86, 0x60, 0x0f, 0x71, 0x1b, 0x49, 0xea, 0xc1, 0x42, 0x40, 0x0f, 0xcd,
	0xf7, 0x41, 0x10, 0x75, 0x30, 0x0d, 0x46, 0x60, 0x7f, 0x12, 0xd6, 0x60, 0x04, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x02, 0x26, 0x04, 0x68, 0x01, 0x00, 0x00,
}
